[package]
name = "corrosionwm"
version = "0.1.0"
edition = "2021"
authors = ["CorrosionWM Developers"]
description = "A aesthetic Wayland compositor written in Rust"
repository = "https://github.com/corrosionwm/corrosionwm"
license = "MIT"
readme = "README.md"
keywords = ["wayland", "compositor", "rust"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calloop = "0.10.5"
smithay = { git = "https://github.com/Smithay/smithay", features = [ "backend_winit", "wayland_frontend", "desktop", ] }
slog = "2.7.0"
slog-term = "2.9.0"
slog-async = "2.7.0"
slog-stdlog = "4.1.1"
slog-scope = "4.4.0"
xcursor = "0.3.4"
image = "0.24.5"
renderdoc = "0.10.1"
bitflags = "1.3.2"
